name: Release

on:
  push:
    tags:
      - v*

jobs:

  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Checkout released tag
      run: |
        echo ::set-env name=RELEASE_VERSION::${GITHUB_REF#refs/tags/v}

    - name: Set up Docker Buildx
      uses: crazy-max/ghaction-docker-buildx@v3

    - name: Login to docker.io registry
      run: |
        echo ${{ secrets. DOCKER_REGISTRY_PASSWORD }} | docker login --username wsmoogle --password-stdin

    - name: Cache Docker layers
      uses: actions/cache@v2
      id: cache
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Docker Buildx (push)
      run: |
        docker buildx build \
          --cache-from "type=local,src=/tmp/.buildx-cache" \
          --cache-to "type=local,dest=/tmp/.buildx-cache" \
          --platform linux/amd64 \
          --output "type=image,push=true" \
          --tag weseek/nginx-nchan:${{ env.RELEASE_VERSION }} \
          --tag weseek/nginx-nchan:latest \
          --file ./mainline/Dockerfile ./mainline

    - name: Slack Notification
      uses: weseek/ghaction-release-slack-notification@master
      with:
        channel: '#dev'
        url: ${{ secrets.SLACK_WEBHOOK_URL }}
        created_tag: 'v${{ env.RELEASE_VERSION }}'
